favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: /themes/custom/bookstore/favicon.ico
  use_default: 1
schemas:
  bootstrap: 8000
  bookstore: 8000
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: 'public://icon.png'
  url: null
  use_default: 1
table_responsive: '-1'
cdn_theme: bootstrap
cdn_cache_ttl_versions: '604800'
cdn_cache_ttl_themes: '604800'
cdn_cache_ttl_assets: '0'
cdn_cache_ttl_library: '0'
apply: Apply
reset_http_request_cache: ''
table: ''
table_bordered: 1
breadcrumb_home: 1
breadcrumb: '0'
